In [1]:
"""Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.
"""

'Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.\n'

In [2]:
import scipy.stats as stats
import statsmodels.api as sm
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from PIL import ImageGrab
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
print(' We are going to conduct a Test of Independence using Chi-Square x2 test with Contingency table \n We need to check whether the proportion of any of these samples are different or the same? \n  ')

 We are going to conduct a Test of Independence using Chi-Square x2 test with Contingency table 
 We need to check whether the proportion of any of these samples are different or the same? 
  


In [4]:
print(' Step 1: \n Make two Hypothesis one contradicting to other \n Null Hypothesis is want we want to prove \n Null Hypothesis: There is no association or dependency between the gender based buyer rations across regions  \n Alternative Hypthosis: There is a significant association or dependency between the gender based buyer rations across regions')

 Step 1: 
 Make two Hypothesis one contradicting to other 
 Null Hypothesis is want we want to prove 
 Null Hypothesis: There is no association or dependency between the gender based buyer rations across regions  
 Alternative Hypthosis: There is a significant association or dependency between the gender based buyer rations across regions


In [5]:
print(' Step 2: \n Decide a cut-off value \n Significance 5% \n alpha = 0.05 \n As it is a one-tailed test \n alpha = 1-0.95 = 0.05')

 Step 2: 
 Decide a cut-off value 
 Significance 5% 
 alpha = 0.05 
 As it is a one-tailed test 
 alpha = 1-0.95 = 0.05


In [6]:
print(' Step 3: \n Collect evidence \n Importing Files \n ')

 Step 3: 
 Collect evidence 
 Importing Files 
 


In [7]:
buyer = pd.read_csv(r'C:\Users\pv437\Desktop\Data Scince Folder\assignment\assignment downloads\ass3\BuyerRatio.csv', index_col = 0)
buyer

East  West  North  South
Observed Values                          
Males              50   142    131     70
Females           435  1523   1356    750

In [8]:
table = [[50,142,131,70],
        [435,1523,1356,750]]
table

[[50, 142, 131, 70], [435, 1523, 1356, 750]]

In [9]:
'''Applying Chi-Square x2 contingency table to convert observed value into expected value'''
stat, p, dof, exp = stats.chi2_contingency(buyer) 
print(stat,"\n", p,"\n", dof,"\n", exp)


1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [10]:
stats.chi2_contingency(table) 

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [11]:
observed = np.array([50, 142, 131, 70, 435, 1523, 1356, 750])
expected = np.array([42.76531299,  146.81287862,  131.11756787, 72.30424052, 442.23468701, 1518.18712138, 1355.88243213, 747.69575948])

In [12]:
print(' Step 4: \n Comparing Evidence with Hypothesis')

 Step 4: 
 Comparing Evidence with Hypothesis


In [13]:
statistics, p_value = stats.chisquare(observed, expected, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [14]:
print(' Compare p_value with alpha (Significane Level) \n If p_value is !=alpha we failed to reject Null Hypothesis because of lack of evidence  \n If p_value is =alpha we reject Null Hypothesis \n interpreting p-value')

 Compare p_value with alpha (Significane Level) 
 If p_value is !=alpha we failed to reject Null Hypothesis because of lack of evidence  
 If p_value is =alpha we reject Null Hypothesis 
 interpreting p-value


In [15]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.810
We fail to reject Null hypothesis


In [16]:
'''We fail to reject Null Hypothesis because of lack evidence. Therefore, there is no association or dependency between male-female buyers rations and are similar across regions. Hence, Independent samples'''

'We fail to reject Null Hypothesis because of lack evidence. Therefore, there is no association or dependency between male-female buyers rations and are similar across regions. Hence, Independent samples'